import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
      <header>
          <nav>
            <ul>
              <li><Link href="/sign-up">Sign In</Link></li>
              <li><Link href="/sign-in">Sign Up</Link></li>
            </ul>
          </nav>
        </header>
      
        <SignedIn>
          <UserButton />
        </SignedIn>
        {children}
      </body>
      </html>
    </ClerkProvider>
  );
}
